In [2]:
import cv2
import numpy as np
import pandas as pd

In [ ]:
img=cv2.imread('noidea.jpg')
cv2.imshow('Images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread('noidea.jpg')
img=cv2.resize(img,(300,200))
cv2.imshow('Images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread('noidea.jpg')
img=cv2.resize(img,(300,200))
img_2=np.hstack((img,img))
img_4=np.vstack((img_2,img_2))
cv2.imshow('Images',img_4)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Video Access

In [ ]:
video=cv2.VideoCapture('Champion (Official Song).mp4')
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(600,400))
        cv2.imshow("video player",video1)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

In [ ]:
video=cv2.VideoCapture('Champion (Official Song).mp4')
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(600,400))
        video2=np.hstack((video1,video1))
        video4=np.vstack((video2,video2))
        cv2.imshow("video player",video4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()


# Access your system camera

In [ ]:
video=cv2.VideoCapture(0)
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(600,400))
        cv2.imshow("video player",video1)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

In [ ]:
video=cv2.VideoCapture(0)
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(600,400))
        video2=np.hstack((video1,video1))
        video4=np.vstack((video2,video2))
        cv2.imshow("video player",video4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

# Different Different View in a grid

In [7]:
camera_view=cv2.VideoCapture(0)
video1=cv2.VideoCapture('Champion (Official Song).mp4')
video2=cv2.VideoCapture('Waka Waka.mp4')
video3=cv2.VideoCapture('O Antava.mp4')
while camera_view.isOpened():
    ret1,frame=camera_view.read()
    ret2,frame2=video1.read()
    ret3,frame3=video2.read()
    if ret1:
        frame=cv2.resize(frame,(600,300))
        frame2=cv2.resize(frame2,(600,300))
        frame3=cv2.resize(frame3,(600,300))
        image=cv2.imread('noidea.jpg')
        image=cv2.resize(image,(600,300))
        
        frame_2=np.hstack((frame,frame2))
        frame_02=np.hstack((frame3,image))
        frame_4=np.vstack((frame_2,frame_02))
        cv2.imshow("video player",frame_4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
camera_view.release()
cv2.destroyAllWindows()

In [8]:
import cv2

In [16]:
img=cv2.imread('noidea.jpg')
print(img)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img.shape)

[[[188 144  83]
  [188 144  83]
  [188 144  83]
  ...
  [200 151 107]
  [200 151 107]
  [202 151 108]]

 [[189 145  84]
  [188 144  83]
  [188 144  83]
  ...
  [200 151 107]
  [200 151 107]
  [202 151 108]]

 [[189 145  84]
  [189 145  84]
  [189 145  84]
  ...
  [201 152 108]
  [201 152 108]
  [202 151 108]]

 ...

 [[132 170 200]
  [137 168 201]
  [143 168 202]
  ...
  [145 147 141]
  [ 35  37  31]
  [ 23  24  22]]

 [[113 172 198]
  [116 169 196]
  [121 167 198]
  ...
  [ 14  16  10]
  [ 24  26  20]
  [ 26  27  25]]

 [[117 172 187]
  [119 167 185]
  [125 166 188]
  ...
  [ 25  26  22]
  [ 19  20  16]
  [ 21  22  20]]]
(414, 625, 3)


In [18]:
img_g=cv2.imread('noidea.jpg',0)
print(img_g)
cv2.imshow('image_grey',img_g)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img_g.shape)

[[131 131 131 ... 143 143 144]
 [132 131 131 ... 143 143 144]
 [132 132 132 ... 144 144 144]
 ...
 [175 174 175 ... 145  35  23]
 [173 171 171 ...  14  24  26]
 [170 167 168 ...  25  19  21]]
(414, 625)


In [17]:
img_rgb=cv2.imread('noidea.jpg',1)
print(img_rgb)
cv2.imshow('image',img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img_rgb.shape)

[[[188 144  83]
  [188 144  83]
  [188 144  83]
  ...
  [200 151 107]
  [200 151 107]
  [202 151 108]]

 [[189 145  84]
  [188 144  83]
  [188 144  83]
  ...
  [200 151 107]
  [200 151 107]
  [202 151 108]]

 [[189 145  84]
  [189 145  84]
  [189 145  84]
  ...
  [201 152 108]
  [201 152 108]
  [202 151 108]]

 ...

 [[132 170 200]
  [137 168 201]
  [143 168 202]
  ...
  [145 147 141]
  [ 35  37  31]
  [ 23  24  22]]

 [[113 172 198]
  [116 169 196]
  [121 167 198]
  ...
  [ 14  16  10]
  [ 24  26  20]
  [ 26  27  25]]

 [[117 172 187]
  [119 167 185]
  [125 166 188]
  ...
  [ 25  26  22]
  [ 19  20  16]
  [ 21  22  20]]]
(414, 625, 3)


# Generated img

In [24]:
rand_arr=np.random.randint(255,size=(300,600,3))
cv2.imwrite("images1.png",rand_arr)

True

In [25]:
img_rand=cv2.imread("images1.jpg")
cv2.imshow('Rand_img',img_rand)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
img_n=cv2.imread("noidea.jpg")
cv2.imshow('image',img_n)

cv2.imwrite("AI_generated.png",img_n)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
'''import os
os.mkdir('video_to_img')
video=cv2.VideoCapture('Champion (Official Song).mp4')
img_count=1

while video.isOpened():
    ret,frame=video.read()
    
    if not ret:
        print("Unable to read frames")
        break
    is_img_write=cv2.imwrite(f"video_to_img\img{img_count}.jpeg",frame)
    
    if is_img_write:
        print(f'image save at video_to_image\img{img_count}.jpeg')

    cv2.imshow("video",frame)
        
    cv2.waitKey(25) & 0xff==ord('q')
    img_count +=1

video.release()
cv2.destroyAllWindows()'''

image save at video_to_image\img1.jpeg
image save at video_to_image\img2.jpeg
image save at video_to_image\img3.jpeg
image save at video_to_image\img4.jpeg
image save at video_to_image\img5.jpeg
image save at video_to_image\img6.jpeg
image save at video_to_image\img7.jpeg
image save at video_to_image\img8.jpeg
image save at video_to_image\img9.jpeg
image save at video_to_image\img10.jpeg
image save at video_to_image\img11.jpeg
image save at video_to_image\img12.jpeg
image save at video_to_image\img13.jpeg
image save at video_to_image\img14.jpeg
image save at video_to_image\img15.jpeg
image save at video_to_image\img16.jpeg
image save at video_to_image\img17.jpeg
image save at video_to_image\img18.jpeg
image save at video_to_image\img19.jpeg
image save at video_to_image\img20.jpeg
image save at video_to_image\img21.jpeg
image save at video_to_image\img22.jpeg
image save at video_to_image\img23.jpeg
image save at video_to_image\img24.jpeg
image save at video_to_image\img25.jpeg
image sav

image save at video_to_image\img204.jpeg
image save at video_to_image\img205.jpeg
image save at video_to_image\img206.jpeg
image save at video_to_image\img207.jpeg
image save at video_to_image\img208.jpeg
image save at video_to_image\img209.jpeg
image save at video_to_image\img210.jpeg
image save at video_to_image\img211.jpeg
image save at video_to_image\img212.jpeg
image save at video_to_image\img213.jpeg
image save at video_to_image\img214.jpeg
image save at video_to_image\img215.jpeg
image save at video_to_image\img216.jpeg
image save at video_to_image\img217.jpeg
image save at video_to_image\img218.jpeg
image save at video_to_image\img219.jpeg
image save at video_to_image\img220.jpeg
image save at video_to_image\img221.jpeg
image save at video_to_image\img222.jpeg
image save at video_to_image\img223.jpeg
image save at video_to_image\img224.jpeg
image save at video_to_image\img225.jpeg
image save at video_to_image\img226.jpeg
image save at video_to_image\img227.jpeg
image save at vi

image save at video_to_image\img408.jpeg
image save at video_to_image\img409.jpeg
image save at video_to_image\img410.jpeg
image save at video_to_image\img411.jpeg
image save at video_to_image\img412.jpeg
image save at video_to_image\img413.jpeg
image save at video_to_image\img414.jpeg
image save at video_to_image\img415.jpeg
image save at video_to_image\img416.jpeg
image save at video_to_image\img417.jpeg
image save at video_to_image\img418.jpeg
image save at video_to_image\img419.jpeg
image save at video_to_image\img420.jpeg
image save at video_to_image\img421.jpeg
image save at video_to_image\img422.jpeg
image save at video_to_image\img423.jpeg
image save at video_to_image\img424.jpeg
image save at video_to_image\img425.jpeg
image save at video_to_image\img426.jpeg
image save at video_to_image\img427.jpeg
image save at video_to_image\img428.jpeg
image save at video_to_image\img429.jpeg
image save at video_to_image\img430.jpeg
image save at video_to_image\img431.jpeg
image save at vi

KeyboardInterrupt: 